"""reform english in table vacancies

Revision ID: 1b32dd2b77f8
Revises: bd0bbe82d721
Create Date: 2022-08-29 19:07:01.049656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b32dd2b77f8'
down_revision = 'bd0bbe82d721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('english_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'english', ['english_id'], ['id'], ondelete='NO ACTION')
    op.drop_column('vacancies', 'knowledge_of_english')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('knowledge_of_english', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'english_id')
    # ### end Alembic commands ###
