"""reform table vacancies

Revision ID: bd0bbe82d721
Revises: fa628dea1b2d
Create Date: 2022-08-29 18:05:28.137875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0bbe82d721'
down_revision = 'bc63ec4350c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'citizenship_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vacancies', 'work_experience_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vacancies', 'work_experience_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vacancies', 'citizenship_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
