from .city import CRUDCity
from .citizenship import CRUDCitizenShip
from .applicant_forms import CRUDApplicantForm
from .position import CRUDPosition
from .recent_jobs import CRUDRecentJob
from .work_experiences import CRUDWorkExperience
from .roles import CRUDRole
from .status import CRUDStatus
from .users import CRUDUser
from .vacancy import CRUDVacancy
from .english import CRUDEnglish
from .age import CRUDAge
from .employer_reply import CRUDEmployerReply